/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GithubInstallationRouteImport } from './routes/github.installation'
import { Route as GithubAuthorizationRouteImport } from './routes/github.authorization'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppRepositoriesRepositoryIdRouteImport } from './routes/_app.repositories.$repositoryId'
import { Route as AppBillingSuccessRouteImport } from './routes/_app.billing.success'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubInstallationRoute = GithubInstallationRouteImport.update({
  id: '/github/installation',
  path: '/github/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubAuthorizationRoute = GithubAuthorizationRouteImport.update({
  id: '/github/authorization',
  path: '/github/authorization',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRepositoryIdRoute =
  AppRepositoriesRepositoryIdRouteImport.update({
    id: '/repositories/$repositoryId',
    path: '/repositories/$repositoryId',
    getParentRoute: () => AppRoute,
  } as any)
const AppBillingSuccessRoute = AppBillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppBillingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/github/authorization': typeof GithubAuthorizationRoute
  '/github/installation': typeof GithubInstallationRoute
  '/billing/success': typeof AppBillingSuccessRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/github/authorization': typeof GithubAuthorizationRoute
  '/github/installation': typeof GithubInstallationRoute
  '/billing/success': typeof AppBillingSuccessRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/billing': typeof AppBillingRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/github/authorization': typeof GithubAuthorizationRoute
  '/github/installation': typeof GithubInstallationRoute
  '/_app/billing/success': typeof AppBillingSuccessRoute
  '/_app/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/dashboard'
    | '/github/authorization'
    | '/github/installation'
    | '/billing/success'
    | '/repositories/$repositoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/billing'
    | '/dashboard'
    | '/github/authorization'
    | '/github/installation'
    | '/billing/success'
    | '/repositories/$repositoryId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/github/authorization'
    | '/github/installation'
    | '/_app/billing/success'
    | '/_app/repositories/$repositoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  GithubAuthorizationRoute: typeof GithubAuthorizationRoute
  GithubInstallationRoute: typeof GithubInstallationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/installation': {
      id: '/github/installation'
      path: '/github/installation'
      fullPath: '/github/installation'
      preLoaderRoute: typeof GithubInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/authorization': {
      id: '/github/authorization'
      path: '/github/authorization'
      fullPath: '/github/authorization'
      preLoaderRoute: typeof GithubAuthorizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/$repositoryId': {
      id: '/_app/repositories/$repositoryId'
      path: '/repositories/$repositoryId'
      fullPath: '/repositories/$repositoryId'
      preLoaderRoute: typeof AppRepositoriesRepositoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/success': {
      id: '/_app/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof AppBillingSuccessRouteImport
      parentRoute: typeof AppBillingRoute
    }
  }
}

interface AppBillingRouteChildren {
  AppBillingSuccessRoute: typeof AppBillingSuccessRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingSuccessRoute: AppBillingSuccessRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppRepositoriesRepositoryIdRoute: typeof AppRepositoriesRepositoryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppRepositoriesRepositoryIdRoute: AppRepositoriesRepositoryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  GithubAuthorizationRoute: GithubAuthorizationRoute,
  GithubInstallationRoute: GithubInstallationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
