/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GithubInstallationRouteImport } from './routes/github.installation'
import { Route as GithubAuthorizationRouteImport } from './routes/github.authorization'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRepositoriesRouteImport } from './routes/_app.repositories'
import { Route as AppManageTeamRouteImport } from './routes/_app.manage-team'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppRepositoriesIndexRouteImport } from './routes/_app.repositories.index'
import { Route as AppRepositoriesRepositoryIdRouteImport } from './routes/_app.repositories.$repositoryId'
import { Route as AppBillingSuccessRouteImport } from './routes/_app.billing.success'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubInstallationRoute = GithubInstallationRouteImport.update({
  id: '/github/installation',
  path: '/github/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubAuthorizationRoute = GithubAuthorizationRouteImport.update({
  id: '/github/authorization',
  path: '/github/authorization',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRoute = AppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppRoute,
} as any)
const AppManageTeamRoute = AppManageTeamRouteImport.update({
  id: '/manage-team',
  path: '/manage-team',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesIndexRoute = AppRepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRepositoriesRoute,
} as any)
const AppRepositoriesRepositoryIdRoute =
  AppRepositoriesRepositoryIdRouteImport.update({
    id: '/$repositoryId',
    path: '/$repositoryId',
    getParentRoute: () => AppRepositoriesRoute,
  } as any)
const AppBillingSuccessRoute = AppBillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppBillingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/billing': typeof AppBillingRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/manage-team': typeof AppManageTeamRoute
  '/repositories': typeof AppRepositoriesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/github/authorization': typeof GithubAuthorizationRoute
  '/github/installation': typeof GithubInstallationRoute
  '/billing/success': typeof AppBillingSuccessRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
  '/repositories/': typeof AppRepositoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/billing': typeof AppBillingRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/manage-team': typeof AppManageTeamRoute
  '/settings': typeof AppSettingsRoute
  '/github/authorization': typeof GithubAuthorizationRoute
  '/github/installation': typeof GithubInstallationRoute
  '/billing/success': typeof AppBillingSuccessRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
  '/repositories': typeof AppRepositoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/billing': typeof AppBillingRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/manage-team': typeof AppManageTeamRoute
  '/_app/repositories': typeof AppRepositoriesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/github/authorization': typeof GithubAuthorizationRoute
  '/github/installation': typeof GithubInstallationRoute
  '/_app/billing/success': typeof AppBillingSuccessRoute
  '/_app/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
  '/_app/repositories/': typeof AppRepositoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/manage-team'
    | '/repositories'
    | '/settings'
    | '/github/authorization'
    | '/github/installation'
    | '/billing/success'
    | '/repositories/$repositoryId'
    | '/repositories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/manage-team'
    | '/settings'
    | '/github/authorization'
    | '/github/installation'
    | '/billing/success'
    | '/repositories/$repositoryId'
    | '/repositories'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/manage-team'
    | '/_app/repositories'
    | '/_app/settings'
    | '/github/authorization'
    | '/github/installation'
    | '/_app/billing/success'
    | '/_app/repositories/$repositoryId'
    | '/_app/repositories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  GithubAuthorizationRoute: typeof GithubAuthorizationRoute
  GithubInstallationRoute: typeof GithubInstallationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/installation': {
      id: '/github/installation'
      path: '/github/installation'
      fullPath: '/github/installation'
      preLoaderRoute: typeof GithubInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/authorization': {
      id: '/github/authorization'
      path: '/github/authorization'
      fullPath: '/github/authorization'
      preLoaderRoute: typeof GithubAuthorizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories': {
      id: '/_app/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AppRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage-team': {
      id: '/_app/manage-team'
      path: '/manage-team'
      fullPath: '/manage-team'
      preLoaderRoute: typeof AppManageTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/': {
      id: '/_app/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AppRepositoriesIndexRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
    '/_app/repositories/$repositoryId': {
      id: '/_app/repositories/$repositoryId'
      path: '/$repositoryId'
      fullPath: '/repositories/$repositoryId'
      preLoaderRoute: typeof AppRepositoriesRepositoryIdRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
    '/_app/billing/success': {
      id: '/_app/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof AppBillingSuccessRouteImport
      parentRoute: typeof AppBillingRoute
    }
  }
}

interface AppBillingRouteChildren {
  AppBillingSuccessRoute: typeof AppBillingSuccessRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingSuccessRoute: AppBillingSuccessRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppRepositoriesRouteChildren {
  AppRepositoriesRepositoryIdRoute: typeof AppRepositoriesRepositoryIdRoute
  AppRepositoriesIndexRoute: typeof AppRepositoriesIndexRoute
}

const AppRepositoriesRouteChildren: AppRepositoriesRouteChildren = {
  AppRepositoriesRepositoryIdRoute: AppRepositoriesRepositoryIdRoute,
  AppRepositoriesIndexRoute: AppRepositoriesIndexRoute,
}

const AppRepositoriesRouteWithChildren = AppRepositoriesRoute._addFileChildren(
  AppRepositoriesRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppManageTeamRoute: typeof AppManageTeamRoute
  AppRepositoriesRoute: typeof AppRepositoriesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBillingRoute: AppBillingRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppManageTeamRoute: AppManageTeamRoute,
  AppRepositoriesRoute: AppRepositoriesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  GithubAuthorizationRoute: GithubAuthorizationRoute,
  GithubInstallationRoute: GithubInstallationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
