/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppConnectRouteImport } from './routes/_app.connect'
import { Route as AppWorkspaceSlugRouteImport } from './routes/_app.$workspaceSlug'
import { Route as AppOnboardingUsageRouteImport } from './routes/_app.onboarding.usage'
import { Route as AppOnboardingRepositoriesRouteImport } from './routes/_app.onboarding.repositories'
import { Route as AppOnboardingOverviewRouteImport } from './routes/_app.onboarding.overview'
import { Route as AppOnboardingConnectRouteImport } from './routes/_app.onboarding.connect'
import { Route as AppFeedbackFindingRouteImport } from './routes/_app.feedback.finding'
import { Route as AppWorkspaceSlugSettingsRouteImport } from './routes/_app.$workspaceSlug.settings'
import { Route as AppWorkspaceSlugRepositoriesRouteImport } from './routes/_app.$workspaceSlug.repositories'
import { Route as AppWorkspaceSlugMemoriesRouteImport } from './routes/_app.$workspaceSlug.memories'
import { Route as AppWorkspaceSlugManageTeamRouteImport } from './routes/_app.$workspaceSlug.manage-team'
import { Route as AppWorkspaceSlugBillingRouteImport } from './routes/_app.$workspaceSlug.billing'
import { Route as AppWorkspaceSlugAnalyticsRouteImport } from './routes/_app.$workspaceSlug.analytics'
import { Route as AppWorkspaceSlugRepositoriesIndexRouteImport } from './routes/_app.$workspaceSlug.repositories.index'
import { Route as AppWorkspaceSlugRepositoriesRepositoryIdRouteImport } from './routes/_app.$workspaceSlug.repositories.$repositoryId'
import { Route as AppWorkspaceSlugBillingSuccessRouteImport } from './routes/_app.$workspaceSlug.billing.success'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceSlugRoute = AppWorkspaceSlugRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingUsageRoute = AppOnboardingUsageRouteImport.update({
  id: '/onboarding/usage',
  path: '/onboarding/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRepositoriesRoute =
  AppOnboardingRepositoriesRouteImport.update({
    id: '/onboarding/repositories',
    path: '/onboarding/repositories',
    getParentRoute: () => AppRoute,
  } as any)
const AppOnboardingOverviewRoute = AppOnboardingOverviewRouteImport.update({
  id: '/onboarding/overview',
  path: '/onboarding/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingConnectRoute = AppOnboardingConnectRouteImport.update({
  id: '/onboarding/connect',
  path: '/onboarding/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackFindingRoute = AppFeedbackFindingRouteImport.update({
  id: '/feedback/finding',
  path: '/feedback/finding',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceSlugSettingsRoute =
  AppWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugRepositoriesRoute =
  AppWorkspaceSlugRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugMemoriesRoute =
  AppWorkspaceSlugMemoriesRouteImport.update({
    id: '/memories',
    path: '/memories',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugManageTeamRoute =
  AppWorkspaceSlugManageTeamRouteImport.update({
    id: '/manage-team',
    path: '/manage-team',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugBillingRoute = AppWorkspaceSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugAnalyticsRoute =
  AppWorkspaceSlugAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugRepositoriesIndexRoute =
  AppWorkspaceSlugRepositoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugRepositoriesRoute,
  } as any)
const AppWorkspaceSlugRepositoriesRepositoryIdRoute =
  AppWorkspaceSlugRepositoriesRepositoryIdRouteImport.update({
    id: '/$repositoryId',
    path: '/$repositoryId',
    getParentRoute: () => AppWorkspaceSlugRepositoriesRoute,
  } as any)
const AppWorkspaceSlugBillingSuccessRoute =
  AppWorkspaceSlugBillingSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AppWorkspaceSlugBillingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/connect': typeof AppConnectRoute
  '/$workspaceSlug/analytics': typeof AppWorkspaceSlugAnalyticsRoute
  '/$workspaceSlug/billing': typeof AppWorkspaceSlugBillingRouteWithChildren
  '/$workspaceSlug/manage-team': typeof AppWorkspaceSlugManageTeamRoute
  '/$workspaceSlug/memories': typeof AppWorkspaceSlugMemoriesRoute
  '/$workspaceSlug/repositories': typeof AppWorkspaceSlugRepositoriesRouteWithChildren
  '/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRoute
  '/feedback/finding': typeof AppFeedbackFindingRoute
  '/onboarding/connect': typeof AppOnboardingConnectRoute
  '/onboarding/overview': typeof AppOnboardingOverviewRoute
  '/onboarding/repositories': typeof AppOnboardingRepositoriesRoute
  '/onboarding/usage': typeof AppOnboardingUsageRoute
  '/$workspaceSlug/billing/success': typeof AppWorkspaceSlugBillingSuccessRoute
  '/$workspaceSlug/repositories/$repositoryId': typeof AppWorkspaceSlugRepositoriesRepositoryIdRoute
  '/$workspaceSlug/repositories/': typeof AppWorkspaceSlugRepositoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/connect': typeof AppConnectRoute
  '/$workspaceSlug/analytics': typeof AppWorkspaceSlugAnalyticsRoute
  '/$workspaceSlug/billing': typeof AppWorkspaceSlugBillingRouteWithChildren
  '/$workspaceSlug/manage-team': typeof AppWorkspaceSlugManageTeamRoute
  '/$workspaceSlug/memories': typeof AppWorkspaceSlugMemoriesRoute
  '/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRoute
  '/feedback/finding': typeof AppFeedbackFindingRoute
  '/onboarding/connect': typeof AppOnboardingConnectRoute
  '/onboarding/overview': typeof AppOnboardingOverviewRoute
  '/onboarding/repositories': typeof AppOnboardingRepositoriesRoute
  '/onboarding/usage': typeof AppOnboardingUsageRoute
  '/$workspaceSlug/billing/success': typeof AppWorkspaceSlugBillingSuccessRoute
  '/$workspaceSlug/repositories/$repositoryId': typeof AppWorkspaceSlugRepositoriesRepositoryIdRoute
  '/$workspaceSlug/repositories': typeof AppWorkspaceSlugRepositoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/_app/connect': typeof AppConnectRoute
  '/_app/$workspaceSlug/analytics': typeof AppWorkspaceSlugAnalyticsRoute
  '/_app/$workspaceSlug/billing': typeof AppWorkspaceSlugBillingRouteWithChildren
  '/_app/$workspaceSlug/manage-team': typeof AppWorkspaceSlugManageTeamRoute
  '/_app/$workspaceSlug/memories': typeof AppWorkspaceSlugMemoriesRoute
  '/_app/$workspaceSlug/repositories': typeof AppWorkspaceSlugRepositoriesRouteWithChildren
  '/_app/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRoute
  '/_app/feedback/finding': typeof AppFeedbackFindingRoute
  '/_app/onboarding/connect': typeof AppOnboardingConnectRoute
  '/_app/onboarding/overview': typeof AppOnboardingOverviewRoute
  '/_app/onboarding/repositories': typeof AppOnboardingRepositoriesRoute
  '/_app/onboarding/usage': typeof AppOnboardingUsageRoute
  '/_app/$workspaceSlug/billing/success': typeof AppWorkspaceSlugBillingSuccessRoute
  '/_app/$workspaceSlug/repositories/$repositoryId': typeof AppWorkspaceSlugRepositoriesRepositoryIdRoute
  '/_app/$workspaceSlug/repositories/': typeof AppWorkspaceSlugRepositoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$workspaceSlug'
    | '/connect'
    | '/$workspaceSlug/analytics'
    | '/$workspaceSlug/billing'
    | '/$workspaceSlug/manage-team'
    | '/$workspaceSlug/memories'
    | '/$workspaceSlug/repositories'
    | '/$workspaceSlug/settings'
    | '/feedback/finding'
    | '/onboarding/connect'
    | '/onboarding/overview'
    | '/onboarding/repositories'
    | '/onboarding/usage'
    | '/$workspaceSlug/billing/success'
    | '/$workspaceSlug/repositories/$repositoryId'
    | '/$workspaceSlug/repositories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$workspaceSlug'
    | '/connect'
    | '/$workspaceSlug/analytics'
    | '/$workspaceSlug/billing'
    | '/$workspaceSlug/manage-team'
    | '/$workspaceSlug/memories'
    | '/$workspaceSlug/settings'
    | '/feedback/finding'
    | '/onboarding/connect'
    | '/onboarding/overview'
    | '/onboarding/repositories'
    | '/onboarding/usage'
    | '/$workspaceSlug/billing/success'
    | '/$workspaceSlug/repositories/$repositoryId'
    | '/$workspaceSlug/repositories'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/$workspaceSlug'
    | '/_app/connect'
    | '/_app/$workspaceSlug/analytics'
    | '/_app/$workspaceSlug/billing'
    | '/_app/$workspaceSlug/manage-team'
    | '/_app/$workspaceSlug/memories'
    | '/_app/$workspaceSlug/repositories'
    | '/_app/$workspaceSlug/settings'
    | '/_app/feedback/finding'
    | '/_app/onboarding/connect'
    | '/_app/onboarding/overview'
    | '/_app/onboarding/repositories'
    | '/_app/onboarding/usage'
    | '/_app/$workspaceSlug/billing/success'
    | '/_app/$workspaceSlug/repositories/$repositoryId'
    | '/_app/$workspaceSlug/repositories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$workspaceSlug': {
      id: '/_app/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AppWorkspaceSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/usage': {
      id: '/_app/onboarding/usage'
      path: '/onboarding/usage'
      fullPath: '/onboarding/usage'
      preLoaderRoute: typeof AppOnboardingUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/repositories': {
      id: '/_app/onboarding/repositories'
      path: '/onboarding/repositories'
      fullPath: '/onboarding/repositories'
      preLoaderRoute: typeof AppOnboardingRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/overview': {
      id: '/_app/onboarding/overview'
      path: '/onboarding/overview'
      fullPath: '/onboarding/overview'
      preLoaderRoute: typeof AppOnboardingOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/connect': {
      id: '/_app/onboarding/connect'
      path: '/onboarding/connect'
      fullPath: '/onboarding/connect'
      preLoaderRoute: typeof AppOnboardingConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback/finding': {
      id: '/_app/feedback/finding'
      path: '/feedback/finding'
      fullPath: '/feedback/finding'
      preLoaderRoute: typeof AppFeedbackFindingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$workspaceSlug/settings': {
      id: '/_app/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/repositories': {
      id: '/_app/$workspaceSlug/repositories'
      path: '/repositories'
      fullPath: '/$workspaceSlug/repositories'
      preLoaderRoute: typeof AppWorkspaceSlugRepositoriesRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/memories': {
      id: '/_app/$workspaceSlug/memories'
      path: '/memories'
      fullPath: '/$workspaceSlug/memories'
      preLoaderRoute: typeof AppWorkspaceSlugMemoriesRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/manage-team': {
      id: '/_app/$workspaceSlug/manage-team'
      path: '/manage-team'
      fullPath: '/$workspaceSlug/manage-team'
      preLoaderRoute: typeof AppWorkspaceSlugManageTeamRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/billing': {
      id: '/_app/$workspaceSlug/billing'
      path: '/billing'
      fullPath: '/$workspaceSlug/billing'
      preLoaderRoute: typeof AppWorkspaceSlugBillingRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/analytics': {
      id: '/_app/$workspaceSlug/analytics'
      path: '/analytics'
      fullPath: '/$workspaceSlug/analytics'
      preLoaderRoute: typeof AppWorkspaceSlugAnalyticsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/repositories/': {
      id: '/_app/$workspaceSlug/repositories/'
      path: '/'
      fullPath: '/$workspaceSlug/repositories/'
      preLoaderRoute: typeof AppWorkspaceSlugRepositoriesIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugRepositoriesRoute
    }
    '/_app/$workspaceSlug/repositories/$repositoryId': {
      id: '/_app/$workspaceSlug/repositories/$repositoryId'
      path: '/$repositoryId'
      fullPath: '/$workspaceSlug/repositories/$repositoryId'
      preLoaderRoute: typeof AppWorkspaceSlugRepositoriesRepositoryIdRouteImport
      parentRoute: typeof AppWorkspaceSlugRepositoriesRoute
    }
    '/_app/$workspaceSlug/billing/success': {
      id: '/_app/$workspaceSlug/billing/success'
      path: '/success'
      fullPath: '/$workspaceSlug/billing/success'
      preLoaderRoute: typeof AppWorkspaceSlugBillingSuccessRouteImport
      parentRoute: typeof AppWorkspaceSlugBillingRoute
    }
  }
}

interface AppWorkspaceSlugBillingRouteChildren {
  AppWorkspaceSlugBillingSuccessRoute: typeof AppWorkspaceSlugBillingSuccessRoute
}

const AppWorkspaceSlugBillingRouteChildren: AppWorkspaceSlugBillingRouteChildren =
  {
    AppWorkspaceSlugBillingSuccessRoute: AppWorkspaceSlugBillingSuccessRoute,
  }

const AppWorkspaceSlugBillingRouteWithChildren =
  AppWorkspaceSlugBillingRoute._addFileChildren(
    AppWorkspaceSlugBillingRouteChildren,
  )

interface AppWorkspaceSlugRepositoriesRouteChildren {
  AppWorkspaceSlugRepositoriesRepositoryIdRoute: typeof AppWorkspaceSlugRepositoriesRepositoryIdRoute
  AppWorkspaceSlugRepositoriesIndexRoute: typeof AppWorkspaceSlugRepositoriesIndexRoute
}

const AppWorkspaceSlugRepositoriesRouteChildren: AppWorkspaceSlugRepositoriesRouteChildren =
  {
    AppWorkspaceSlugRepositoriesRepositoryIdRoute:
      AppWorkspaceSlugRepositoriesRepositoryIdRoute,
    AppWorkspaceSlugRepositoriesIndexRoute:
      AppWorkspaceSlugRepositoriesIndexRoute,
  }

const AppWorkspaceSlugRepositoriesRouteWithChildren =
  AppWorkspaceSlugRepositoriesRoute._addFileChildren(
    AppWorkspaceSlugRepositoriesRouteChildren,
  )

interface AppWorkspaceSlugRouteChildren {
  AppWorkspaceSlugAnalyticsRoute: typeof AppWorkspaceSlugAnalyticsRoute
  AppWorkspaceSlugBillingRoute: typeof AppWorkspaceSlugBillingRouteWithChildren
  AppWorkspaceSlugManageTeamRoute: typeof AppWorkspaceSlugManageTeamRoute
  AppWorkspaceSlugMemoriesRoute: typeof AppWorkspaceSlugMemoriesRoute
  AppWorkspaceSlugRepositoriesRoute: typeof AppWorkspaceSlugRepositoriesRouteWithChildren
  AppWorkspaceSlugSettingsRoute: typeof AppWorkspaceSlugSettingsRoute
}

const AppWorkspaceSlugRouteChildren: AppWorkspaceSlugRouteChildren = {
  AppWorkspaceSlugAnalyticsRoute: AppWorkspaceSlugAnalyticsRoute,
  AppWorkspaceSlugBillingRoute: AppWorkspaceSlugBillingRouteWithChildren,
  AppWorkspaceSlugManageTeamRoute: AppWorkspaceSlugManageTeamRoute,
  AppWorkspaceSlugMemoriesRoute: AppWorkspaceSlugMemoriesRoute,
  AppWorkspaceSlugRepositoriesRoute:
    AppWorkspaceSlugRepositoriesRouteWithChildren,
  AppWorkspaceSlugSettingsRoute: AppWorkspaceSlugSettingsRoute,
}

const AppWorkspaceSlugRouteWithChildren =
  AppWorkspaceSlugRoute._addFileChildren(AppWorkspaceSlugRouteChildren)

interface AppRouteChildren {
  AppWorkspaceSlugRoute: typeof AppWorkspaceSlugRouteWithChildren
  AppConnectRoute: typeof AppConnectRoute
  AppFeedbackFindingRoute: typeof AppFeedbackFindingRoute
  AppOnboardingConnectRoute: typeof AppOnboardingConnectRoute
  AppOnboardingOverviewRoute: typeof AppOnboardingOverviewRoute
  AppOnboardingRepositoriesRoute: typeof AppOnboardingRepositoriesRoute
  AppOnboardingUsageRoute: typeof AppOnboardingUsageRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceSlugRoute: AppWorkspaceSlugRouteWithChildren,
  AppConnectRoute: AppConnectRoute,
  AppFeedbackFindingRoute: AppFeedbackFindingRoute,
  AppOnboardingConnectRoute: AppOnboardingConnectRoute,
  AppOnboardingOverviewRoute: AppOnboardingOverviewRoute,
  AppOnboardingRepositoriesRoute: AppOnboardingRepositoriesRoute,
  AppOnboardingUsageRoute: AppOnboardingUsageRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
