export type DocSourceConfig = {
  slug: string
  name: string
  llmsTxtUrl: string
  aliases?: string[]
}

export const docSourceConfigs: DocSourceConfig[] = [
  {
    slug: "stripe",
    name: "Stripe",
    llmsTxtUrl: "https://docs.stripe.com/llms.txt",
    aliases: ["stripe-node", "@stripe/stripe-js"],
  },
  {
    slug: "vercel",
    name: "Vercel",
    llmsTxtUrl: "https://vercel.com/docs/llms.txt",
    aliases: ["@vercel/node", "vercel-cli"],
  },
  {
    slug: "convex",
    name: "Convex",
    llmsTxtUrl: "https://docs.convex.dev/llms.txt",
    aliases: ["convex-dev"],
  },
  {
    slug: "supabase",
    name: "Supabase",
    llmsTxtUrl: "https://supabase.com/llms.txt",
    aliases: ["@supabase/supabase-js"],
  },
  {
    slug: "ai-sdk",
    name: "Vercel AI SDK",
    llmsTxtUrl: "https://ai-sdk.dev/llms.txt",
    aliases: ["ai", "@ai-sdk/react", "@ai-sdk/provider"],
  },
  {
    slug: "temporal",
    name: "Temporal",
    llmsTxtUrl: "https://docs.temporal.io/llms.txt",
    aliases: ["@temporalio/client", "@temporalio/worker", "temporalio"],
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    llmsTxtUrl: "https://platform.claude.com/llms.txt",
    aliases: ["claude", "@anthropic-ai/sdk"],
  },
  {
    slug: "pinecone",
    name: "Pinecone",
    llmsTxtUrl: "https://docs.pinecone.io/llms.txt",
    aliases: ["@pinecone-database/pinecone", "pinecone-client"],
  },
  {
    slug: "resend",
    name: "Resend",
    llmsTxtUrl: "https://resend.com/docs/llms.txt",
  },
  {
    slug: "clerk",
    name: "Clerk",
    llmsTxtUrl: "https://clerk.com/docs/llms.txt",
    aliases: ["@clerk/nextjs", "@clerk/clerk-react"],
  },
  {
    slug: "prisma",
    name: "Prisma",
    llmsTxtUrl: "https://www.prisma.io/docs/llms.txt",
    aliases: ["@prisma/client", "prisma-client"],
  },
  {
    slug: "drizzle",
    name: "Drizzle ORM",
    llmsTxtUrl: "https://orm.drizzle.team/llms.txt",
    aliases: ["drizzle-orm", "drizzle-kit"],
  },
  {
    slug: "trigger-dev",
    name: "Trigger.dev",
    llmsTxtUrl: "https://trigger.dev/docs/llms.txt",
    aliases: ["trigger.dev", "@trigger.dev/sdk", "@trigger.dev/sdk/v3"],
  },
  {
    slug: "neon",
    name: "Neon",
    llmsTxtUrl: "https://neon.com/docs/llms.txt",
    aliases: ["@neondatabase/serverless"],
  },
  {
    slug: "upstash",
    name: "Upstash",
    llmsTxtUrl: "https://upstash.com/docs/llms.txt",
    aliases: ["@upstash/redis", "@upstash/qstash"],
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    llmsTxtUrl: "https://developers.cloudflare.com/llms.txt",
    aliases: ["wrangler", "cloudflare-workers"],
  },
  {
    slug: "zod",
    name: "Zod",
    llmsTxtUrl: "https://zod.dev/llms.txt",
  },
  {
    slug: "turso",
    name: "Turso",
    llmsTxtUrl: "https://docs.turso.tech/llms.txt",
    aliases: ["@libsql/client", "libsql"],
  },
  {
    slug: "firecrawl",
    name: "Firecrawl",
    llmsTxtUrl: "https://docs.firecrawl.dev/llms.txt",
    aliases: ["@mendable/firecrawl-js", "firecrawl-py"],
  },
  {
    slug: "browserbase",
    name: "Browserbase",
    llmsTxtUrl: "https://docs.browserbase.com/llms.txt",
    aliases: ["@browserbasehq/sdk"],
  },
  {
    slug: "railway",
    name: "Railway",
    llmsTxtUrl: "https://docs.railway.com/llms.txt",
    aliases: ["railway-app", "@railway/cli"],
  },
  {
    slug: "qdrant",
    name: "Qdrant",
    llmsTxtUrl: "https://qdrant.tech/llms.txt",
    aliases: ["@qdrant/js-client-rest", "qdrant-client"],
  },
  {
    slug: "groq",
    name: "Groq",
    llmsTxtUrl: "https://console.groq.com/llms.txt",
    aliases: ["groq-sdk"],
  },
  {
    slug: "modal",
    name: "Modal",
    llmsTxtUrl: "https://modal.com/llms.txt",
    aliases: ["modal-client"],
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    llmsTxtUrl: "https://docs.perplexity.ai/llms.txt",
    aliases: ["perplexity-ai"],
  },
  {
    slug: "together-ai",
    name: "Together AI",
    llmsTxtUrl: "https://docs.together.ai/llms.txt",
    aliases: ["together-ai"],
  },
  {
    slug: "wandb",
    name: "Weights & Biases",
    llmsTxtUrl: "https://docs.wandb.ai/llms.txt",
    aliases: ["weights-and-biases"],
  },
  {
    slug: "docker",
    name: "Docker",
    llmsTxtUrl: "https://docs.docker.com/llms.txt",
    aliases: ["docker-compose", "dockerode"],
  },
  {
    slug: "duckdb",
    name: "DuckDB",
    llmsTxtUrl: "https://duckdb.org/llms.txt",
    aliases: ["@duckdb/node-api", "duckdb-async"],
  },
  {
    slug: "netlify",
    name: "Netlify",
    llmsTxtUrl: "https://docs.netlify.com/llms.txt",
    aliases: ["netlify-cli", "@netlify/functions"],
  },
  {
    slug: "pulumi",
    name: "Pulumi",
    llmsTxtUrl: "https://www.pulumi.com/llms.txt",
    aliases: ["@pulumi/pulumi", "pulumi-cli"],
  },
  {
    slug: "redis",
    name: "Redis",
    llmsTxtUrl: "https://redis.io/llms.txt",
    aliases: ["redis", "ioredis", "@redis/client"],
  },
  {
    slug: "turborepo",
    name: "Turborepo",
    llmsTxtUrl: "https://turborepo.com/llms.txt",
    aliases: ["turbo", "turbo-build"],
  },
  {
    slug: "auth0",
    name: "Auth0",
    llmsTxtUrl: "https://auth0.com/llms.txt",
    aliases: ["@auth0/auth0-react", "@auth0/nextjs-auth0", "auth0-js"],
  },
  {
    slug: "workos",
    name: "WorkOS",
    llmsTxtUrl: "https://workos.com/docs/llms.txt",
    aliases: ["@workos-inc/node", "@workos-inc/authkit-nextjs"],
  },
  {
    slug: "postmark",
    name: "Postmark",
    llmsTxtUrl: "https://postmarkapp.com/llms.txt",
    aliases: ["postmark"],
  },
  {
    slug: "wordpress",
    name: "WordPress",
    llmsTxtUrl: "https://wordpress.org/llms.txt",
    aliases: ["@wordpress/api-fetch", "@wordpress/scripts", "wp-cli"],
  },
  {
    slug: "inngest",
    name: "Inngest",
    llmsTxtUrl: "https://www.inngest.com/llms.txt",
    aliases: ["inngest"],
  },
  {
    slug: "arcjet",
    name: "Arcjet",
    llmsTxtUrl: "https://docs.arcjet.com/llms.txt",
    aliases: ["@arcjet/node", "@arcjet/next", "@arcjet/react-native"],
  },
  {
    slug: "unkey",
    name: "Unkey",
    llmsTxtUrl: "https://www.unkey.com/docs/llms.txt",
    aliases: ["@unkey/api", "@unkey/ratelimit"],
  },
  {
    slug: "novu",
    name: "Novu",
    llmsTxtUrl: "https://docs.novu.co/llms.txt",
    aliases: ["@novu/api", "@novu/node", "@novu/react"],
  },
  {
    slug: "statsig",
    name: "Statsig",
    llmsTxtUrl: "https://docs.statsig.com/llms.txt",
    aliases: ["@statsig/js-client", "statsig-node", "statsig-react"],
  },
  {
    slug: "axiom",
    name: "Axiom",
    llmsTxtUrl: "https://axiom.co/docs/llms.txt",
    aliases: ["@axiomhq/js", "@axiomhq/logging"],
  },
  {
    slug: "clickhouse",
    name: "ClickHouse",
    llmsTxtUrl: "https://clickhouse.com/docs/llms.txt",
    aliases: ["@clickhouse/client", "clickhouse-js"],
  },
  {
    slug: "infisical",
    name: "Infisical",
    llmsTxtUrl: "https://infisical.com/docs/llms.txt",
    aliases: ["@infisical/sdk", "infisical-node"],
  },
  {
    slug: "cloudinary",
    name: "Cloudinary",
    llmsTxtUrl: "https://cloudinary.com/documentation/llms.txt",
    aliases: ["cloudinary", "@cloudinary/url-gen", "next-cloudinary"],
  },
  {
    slug: "twilio",
    name: "Twilio",
    llmsTxtUrl: "https://www.twilio.com/docs/llms.txt",
    aliases: ["twilio", "@twilio/voice-sdk"],
  },
  {
    slug: "base-ui",
    name: "Base UI",
    llmsTxtUrl: "https://base-ui.com/llms.txt",
    aliases: ["@base-ui/react"],
  },
  {
    slug: "tanstack",
    name: "TanStack",
    llmsTxtUrl: "https://tanstack.com/llms.txt",
    aliases: [
      "@tanstack/react-query",
      "@tanstack/query-core",
      "@tanstack/react-table",
      "@tanstack/react-form",
      "@tanstack/react-virtual",
    ],
  },
  {
    slug: "storybook",
    name: "Storybook",
    llmsTxtUrl: "https://storybook.js.org/llms.txt",
    aliases: ["storybook", "@storybook/react", "@storybook/nextjs"],
  },
  {
    slug: "livekit",
    name: "LiveKit",
    llmsTxtUrl: "https://docs.livekit.io/llms.txt",
    aliases: ["livekit-client", "livekit-server-sdk", "@livekit/components-react"],
  },
  {
    slug: "ably",
    name: "Ably",
    llmsTxtUrl: "https://ably.com/llms.txt",
    aliases: ["ably", "@ably-labs/react-hooks"],
  },
  {
    slug: "fal-ai",
    name: "fal.ai",
    llmsTxtUrl: "https://docs.fal.ai/llms.txt",
    aliases: ["@fal-ai/client", "@fal-ai/serverless-client"],
  },
  {
    slug: "cohere",
    name: "Cohere",
    llmsTxtUrl: "https://docs.cohere.com/llms.txt",
    aliases: ["cohere-ai"],
  },
  {
    slug: "litellm",
    name: "LiteLLM",
    llmsTxtUrl: "https://docs.litellm.ai/llms.txt",
    aliases: ["litellm", "@litellm/proxy"],
  },
  {
    slug: "deepgram",
    name: "Deepgram",
    llmsTxtUrl: "https://developers.deepgram.com/llms.txt",
    aliases: ["@deepgram/sdk", "@deepgram/agents", "@deepgram/react"],
  },
  {
    slug: "tavily",
    name: "Tavily",
    llmsTxtUrl: "https://docs.tavily.com/llms.txt",
    aliases: ["@tavily/core", "tavily-python"],
  },
  {
    slug: "tinybird",
    name: "Tinybird",
    llmsTxtUrl: "https://www.tinybird.co/docs/llms.txt",
    aliases: ["@tinybirdco/mcp-tinybird", "tinybird-cli"],
  },
  {
    slug: "dagster",
    name: "Dagster",
    llmsTxtUrl: "https://docs.dagster.io/llms.txt",
    aliases: ["dagster", "dagster-cloud"],
  },
  {
    slug: "mapbox",
    name: "Mapbox",
    llmsTxtUrl: "https://docs.mapbox.com/llms.txt",
    aliases: ["mapbox-gl", "@mapbox/mapbox-gl-geocoder", "react-map-gl"],
  },
  {
    slug: "honeycomb",
    name: "Honeycomb",
    llmsTxtUrl: "https://docs.honeycomb.io/llms.txt",
    aliases: ["@honeycombio/opentelemetry-node", "honeycomb-beeline"],
  },
  {
    slug: "meilisearch",
    name: "Meilisearch",
    llmsTxtUrl: "https://www.meilisearch.com/docs/llms.txt",
    aliases: ["meilisearch", "meilisearch-js"],
  },
  {
    slug: "elastic",
    name: "Elastic",
    llmsTxtUrl: "https://www.elastic.co/docs/llms.txt",
    aliases: ["elasticsearch", "@elastic/elasticsearch", "elastic-apm-node"],
  },
  {
    slug: "tldraw",
    name: "tldraw",
    llmsTxtUrl: "https://tldraw.dev/llms.txt",
    aliases: ["tldraw", "@tldraw/editor", "@tldraw/store"],
  },
  {
    slug: "braintrust",
    name: "Braintrust",
    llmsTxtUrl: "https://www.braintrust.dev/docs/llms.txt",
    aliases: ["braintrust", "@braintrustdata/sdk", "autoevals"],
  },
  {
    slug: "pydantic",
    name: "Pydantic",
    llmsTxtUrl: "https://docs.pydantic.dev/latest/llms.txt",
    aliases: ["pydantic", "pydantic-settings"],
  },
  {
    slug: "remotion",
    name: "Remotion",
    llmsTxtUrl: "https://www.remotion.dev/llms.txt",
    aliases: ["remotion", "@remotion/renderer", "@remotion/player"],
  },
  {
    slug: "tiptap",
    name: "Tiptap",
    llmsTxtUrl: "https://tiptap.dev/llms.txt",
    aliases: ["@tiptap/core", "@tiptap/react", "@tiptap/starter-kit"],
  },
  {
    slug: "polar",
    name: "Polar",
    llmsTxtUrl: "https://polar.sh/docs/llms.txt",
    aliases: ["@polar-sh/sdk", "@polar-sh/nextjs"],
  },
  {
    slug: "creem",
    name: "Creem",
    llmsTxtUrl: "https://docs.creem.io/llms.txt",
    aliases: ["creem", "@creem_io/webhook-types"],
  },
  {
    slug: "loops",
    name: "Loops",
    llmsTxtUrl: "https://loops.so/docs/llms.txt",
    aliases: ["loops", "@loops-so/node"],
  },
  {
    slug: "knock",
    name: "Knock",
    llmsTxtUrl: "https://docs.knock.app/llms.txt",
    aliases: ["@knocklabs/node", "@knocklabs/react", "@knocklabs/client"],
  },
  {
    slug: "sentry",
    name: "Sentry",
    llmsTxtUrl: "https://docs.sentry.io/llms.txt",
    aliases: ["@sentry/node", "@sentry/react", "@sentry/nextjs", "sentry-sdk"],
  },
  {
    slug: "mongodb",
    name: "MongoDB",
    llmsTxtUrl: "https://www.mongodb.com/llms.txt",
    aliases: ["mongodb", "mongoose", "@mongodb-js/zstd"],
  },
  {
    slug: "datadog",
    name: "Datadog",
    llmsTxtUrl: "https://docs.datadoghq.com/llms.txt",
    aliases: ["dd-trace", "datadog-metrics", "@datadog/browser-rum"],
  },
  {
    slug: "posthog",
    name: "PostHog",
    llmsTxtUrl: "https://posthog.com/llms.txt",
    aliases: ["posthog-js", "posthog-node", "posthog-python"],
  },
  {
    slug: "apollo-graphql",
    name: "Apollo GraphQL",
    llmsTxtUrl: "https://www.apollographql.com/llms.txt",
    aliases: ["@apollo/client", "@apollo/server", "apollo-server"],
  },
  {
    slug: "shadcn-ui",
    name: "shadcn/ui",
    llmsTxtUrl: "https://ui.shadcn.com/llms.txt",
    aliases: ["shadcn", "shadcn-ui"],
  },
  {
    slug: "vite",
    name: "Vite",
    llmsTxtUrl: "https://vite.dev/llms.txt",
    aliases: ["vite", "@vitejs/plugin-react", "@vitejs/plugin-vue"],
  },
  {
    slug: "launchdarkly",
    name: "LaunchDarkly",
    llmsTxtUrl: "https://launchdarkly.com/docs/llms.txt",
    aliases: ["launchdarkly-node-server-sdk", "launchdarkly-js-client-sdk", "launchdarkly-react-client-sdk"],
  },
  {
    slug: "planetscale",
    name: "PlanetScale",
    llmsTxtUrl: "https://planetscale.com/docs/llms.txt",
    aliases: ["@planetscale/database", "pscale"],
  },
  {
    slug: "render",
    name: "Render",
    llmsTxtUrl: "https://render.com/llms.txt",
    aliases: ["render.com", "render-blueprint"],
  },
  {
    slug: "fly-io",
    name: "Fly.io",
    llmsTxtUrl: "https://fly.io/llms.txt",
    aliases: ["flyctl", "fly-io"],
  },
  {
    slug: "new-relic",
    name: "New Relic",
    llmsTxtUrl: "https://newrelic.com/llms.txt",
    aliases: ["newrelic", "@newrelic/browser-agent"],
  },
  {
    slug: "github",
    name: "GitHub",
    llmsTxtUrl: "https://docs.github.com/llms.txt",
    aliases: ["@octokit/rest", "octokit", "github-actions"],
  },
  {
    slug: "gitlab",
    name: "GitLab",
    llmsTxtUrl: "https://docs.gitlab.com/llms.txt",
    aliases: ["@gitbeaker/rest", "gitlab-ci"],
  },
]

export const resolveDocSourceConfig = (library: string) => {
  const normalized = library.trim().toLowerCase()
  return docSourceConfigs.find(
    (source) =>
      source.slug === normalized ||
      source.name.toLowerCase() === normalized ||
      source.aliases?.some((alias) => alias.toLowerCase() === normalized)
  )
}
